
"""esquema inicial

Revision ID: c3c5639df2de
Revises: 0001_baseline
Create Date: 2026-10-08 04:45:52.040553+00:00

MOTIVO:
- (por qué existe esta migración: módulo, feature, tabla/columnas)
"""

from __future__ import annotations

from typing import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

revision: str = 'c3c5639df2de'
down_revision: str | Sequence[str] | None = '0001_baseline'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchanges',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('type', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`type` IN ('crypto_exchange', 'broker', 'data_vendor')", name='chk_exchanges_type'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_exchanges_name'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('feature_sets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), server_default=sa.text("'1.0.0'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('spec', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('json_valid(`spec`)', name='chk_feature_sets_spec_json'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_feature_sets_name_version'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`code` <> ''", name='chk_roles_code'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_roles_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('strategies',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), server_default=sa.text("'1.0.0'"), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('parameters', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('json_valid(`parameters`)', name='chk_strategies_parameters_json'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_strategies_name_version'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('system_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('component', sa.String(length=32), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('level', sa.String(length=16), server_default=sa.text("'info'"), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.CheckConstraint("`component` IN ('market_data', 'execution', 'scheduler', 'api')", name='chk_system_events_component'),
    sa.CheckConstraint("`level` IN ('info', 'warning', 'error')", name='chk_system_events_level'),
    sa.CheckConstraint('json_valid(`payload`)', name='chk_system_events_payload_json'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_system_events_component_ts', 'system_events', ['component', 'ts'], unique=False)
    op.create_index('idx_system_events_ts', 'system_events', ['ts'], unique=False)
    op.create_table('timeframes',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=8), nullable=False),
    sa.Column('seconds', sa.Integer(), nullable=False),
    sa.CheckConstraint('`seconds` > 0', name='chk_timeframes_seconds'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code', name='uq_timeframes_code'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_table('models',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=32), nullable=False),
    sa.Column('model_type', sa.String(length=32), nullable=False),
    sa.Column('feature_set_id', sa.BigInteger(), nullable=True),
    sa.Column('artifact_uri', sa.String(length=512), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`model_type` IN ('xgboost', 'lightgbm', 'sklearn', 'nn')", name='chk_models_model_type'),
    sa.CheckConstraint("`status` IN ('active', 'deprecated', 'archived')", name='chk_models_status'),
    sa.CheckConstraint('json_valid(`meta`)', name='chk_models_meta_json'),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], name='fk_models_feature_set'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'version', name='uq_models_name_version'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_models_feature_set', 'models', ['feature_set_id'], unique=False)
    op.create_index('idx_models_status', 'models', ['status'], unique=False)
    op.create_table('symbols',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol', sa.String(length=64), nullable=False),
    sa.Column('base_asset', sa.String(length=32), nullable=True),
    sa.Column('quote_asset', sa.String(length=32), nullable=True),
    sa.Column('asset_class', sa.String(length=16), nullable=False),
    sa.Column('tick_size', sa.NUMERIC(precision=30, scale=12), nullable=True),
    sa.Column('lot_size', sa.NUMERIC(precision=30, scale=12), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`asset_class` IN ('crypto', 'metal', 'etf', 'stock', 'forex')", name='chk_symbols_asset_class'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name='fk_symbols_exchange'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('exchange_id', 'symbol', name='uq_symbols_exchange_symbol'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_symbols_asset_class', 'symbols', ['asset_class'], unique=False)
    op.create_index('idx_symbols_exchange', 'symbols', ['exchange_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), server_default=sa.text("'0'"), nullable=False),
    sa.Column('login_locked_until', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('last_login_at', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('token_current_jti', sa.String(length=64), nullable=True),
    sa.Column('otp_code', sa.String(length=255), nullable=True),
    sa.Column('otp_created_at', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('otp_expires_at', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`status` IN ('active', 'blocked', 'disabled')", name='chk_users_status'),
    sa.CheckConstraint('`failed_attempts` >= 0', name='chk_users_failed_attempts'),
    sa.CheckConstraint('`otp_created_at` IS NULL OR `otp_expires_at` IS NULL OR `otp_expires_at` >= `otp_created_at`', name='chk_users_otp_dates'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name='fk_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', name='uq_users_email'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_users_login_locked_until', 'users', ['login_locked_until'], unique=False)
    op.create_index('idx_users_otp_expires', 'users', ['otp_expires_at'], unique=False)
    op.create_index('idx_users_role_id', 'users', ['role_id'], unique=False)
    op.create_index('idx_users_status', 'users', ['status'], unique=False)
    op.create_index('idx_users_token_jti', 'users', ['token_current_jti'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('base_currency', sa.String(length=16), server_default=sa.text("'USD'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'active'"), nullable=False),
    sa.Column('credentials_ref', sa.String(length=255), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`mode` IN ('paper', 'live')", name='chk_accounts_mode'),
    sa.CheckConstraint("`status` IN ('active', 'suspended')", name='chk_accounts_status'),
    sa.CheckConstraint('json_valid(`meta`)', name='chk_accounts_meta_json'),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], name='fk_accounts_exchange'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_accounts_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_accounts_exchange', 'accounts', ['exchange_id'], unique=False)
    op.create_index('idx_accounts_mode', 'accounts', ['mode'], unique=False)
    op.create_index('idx_accounts_user', 'accounts', ['user_id'], unique=False)
    op.create_table('candle_features',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframe_id', sa.SmallInteger(), nullable=False),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), nullable=False),
    sa.Column('feature_set_id', sa.BigInteger(), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('json_valid(`features`)', name='chk_candle_features_json'),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], name='fk_candle_features_set'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name='fk_candle_features_symbol'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name='fk_candle_features_timeframe'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe_id', 'ts', 'feature_set_id', name='uq_candle_features'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_candle_features_lookup', 'candle_features', ['symbol_id', 'timeframe_id', 'ts', 'feature_set_id'], unique=False)
    op.create_table('candles',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('symbol_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframe_id', sa.SmallInteger(), nullable=False),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), nullable=False),
    sa.Column('open', sa.NUMERIC(precision=30, scale=12), nullable=False),
    sa.Column('high', sa.NUMERIC(precision=30, scale=12), nullable=False),
    sa.Column('low', sa.NUMERIC(precision=30, scale=12), nullable=False),
    sa.Column('close', sa.NUMERIC(precision=30, scale=12), nullable=False),
    sa.Column('volume', sa.NUMERIC(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('`high` >= `low`', name='chk_candles_high_low'),
    sa.CheckConstraint('`open` >= 0 AND `high` >= 0 AND `low` >= 0 AND `close` >= 0 AND `volume` >= 0', name='chk_candles_prices'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name='fk_candles_symbol'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name='fk_candles_timeframe'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symbol_id', 'timeframe_id', 'ts', name='uq_candles_symbol_tf_ts'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_candles_symbol_tf_ts', 'candles', ['symbol_id', 'timeframe_id', 'ts'], unique=False)
    op.create_table('datasets',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('symbol_id', sa.BigInteger(), nullable=True),
    sa.Column('timeframe_id', sa.SmallInteger(), nullable=True),
    sa.Column('start_ts', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('end_ts', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('dataset_hash', sa.String(length=128), nullable=True),
    sa.Column('query_spec', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('json_valid(`query_spec`)', name='chk_datasets_query_spec_json'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name='fk_datasets_symbol'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name='fk_datasets_timeframe'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_datasets_symbol_tf', 'datasets', ['symbol_id', 'timeframe_id'], unique=False)
    op.create_table('investors',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('fee_pct', sa.Numeric(precision=5, scale=4), server_default=sa.text("'0.2000'"), nullable=False, comment='Performance fee ej: 0.2000 = 20%'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('`fee_pct` >= 0 AND `fee_pct` <= 1', name='chk_investors_fee_pct'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_investors_user', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', name='uq_investors_user_id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_investors_active', 'investors', ['is_active'], unique=False)
    op.create_table('account_balances',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('asset', sa.String(length=32), nullable=False),
    sa.Column('free', sa.DECIMAL(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('locked', sa.DECIMAL(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('`free` >= 0 AND `locked` >= 0', name='chk_balances_amounts'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_balances_account', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'asset', 'ts', name='uq_balances_account_asset_ts'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_balances_account_ts', 'account_balances', ['account_id', 'ts'], unique=False)
    op.create_table('bots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('strategy_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframe_id', sa.SmallInteger(), nullable=False),
    sa.Column('mode', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'stopped'"), nullable=False),
    sa.Column('risk_params', sa.JSON(), nullable=False),
    sa.Column('started_at', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('stopped_at', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=True),
    sa.Column('feature_set_id', sa.BigInteger(), nullable=True, comment='Feature set de indicadores técnicos que usa este bot'),
    sa.CheckConstraint("`mode` IN ('paper', 'live')", name='chk_bots_mode'),
    sa.CheckConstraint("`status` IN ('running', 'stopped', 'paused', 'error')", name='chk_bots_status'),
    sa.CheckConstraint('json_valid(`risk_params`)', name='chk_bots_risk_params_json'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_bots_account'),
    sa.ForeignKeyConstraint(['feature_set_id'], ['feature_sets.id'], name='fk_bots_feature_set'),
    sa.ForeignKeyConstraint(['strategy_id'], ['strategies.id'], name='fk_bots_strategy'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name='fk_bots_symbol'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name='fk_bots_timeframe'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_bots_account', 'bots', ['account_id'], unique=False)
    op.create_index('idx_bots_feature_set', 'bots', ['feature_set_id'], unique=False)
    op.create_index('idx_bots_status', 'bots', ['status'], unique=False)
    op.create_index('idx_bots_strategy', 'bots', ['strategy_id'], unique=False)
    op.create_index('idx_bots_symbol', 'bots', ['symbol_id'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=False),
    sa.Column('dataset_id', sa.BigInteger(), nullable=True),
    sa.Column('started_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('finished_at', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'running'"), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('params', sa.JSON(), nullable=False),
    sa.Column('logs_uri', sa.String(length=512), nullable=True),
    sa.CheckConstraint("`status` IN ('running', 'success', 'failed')", name='chk_model_runs_status'),
    sa.CheckConstraint('json_valid(`metrics`)', name='chk_model_runs_metrics_json'),
    sa.CheckConstraint('json_valid(`params`)', name='chk_model_runs_params_json'),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], name='fk_model_runs_dataset'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name='fk_model_runs_model', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_model_runs_dataset', 'model_runs', ['dataset_id'], unique=False)
    op.create_index('idx_model_runs_model', 'model_runs', ['model_id', 'started_at'], unique=False)
    op.create_table('alert_rules',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('rule_type', sa.String(length=16), nullable=False),
    sa.Column('rule_spec', sa.JSON(), nullable=False),
    sa.Column('channels', sa.JSON(), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text("'1'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`rule_type` IN ('pnl', 'drawdown', 'signal', 'error', 'price')", name='chk_alert_rules_type'),
    sa.CheckConstraint('json_valid(`channels`)', name='chk_alert_rules_channels_json'),
    sa.CheckConstraint('json_valid(`rule_spec`)', name='chk_alert_rules_rule_spec_json'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_alert_rules_bot'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_alert_rules_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_alert_rules_bot', 'alert_rules', ['bot_id'], unique=False)
    op.create_index('idx_alert_rules_user', 'alert_rules', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('ip', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('data', sa.JSON(), nullable=False),
    sa.CheckConstraint('json_valid(`data`)', name='chk_audit_logs_data_json'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_audit_logs_bot'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_logs_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_audit_logs_bot_ts', 'audit_logs', ['bot_id', 'ts'], unique=False)
    op.create_index('idx_audit_logs_ts', 'audit_logs', ['ts'], unique=False)
    op.create_index('idx_audit_logs_user_ts', 'audit_logs', ['user_id', 'ts'], unique=False)
    op.create_table('managed_accounts',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('investor_id', sa.BigInteger(), nullable=False),
    sa.Column('account_id', sa.BigInteger(), nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('initial_capital', sa.Numeric(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False, comment='Capital inicial aportado por el inversor'),
    sa.Column('high_water_mark', sa.Numeric(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False, comment='Máximo equity histórico alcanzado (base para HWM fee)'),
    sa.Column('period_type', sa.String(length=16), server_default=sa.text("'monthly'"), nullable=False, comment='Frecuencia de facturación: daily | weekly | monthly'),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('1'), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`period_type` IN ('daily', 'weekly', 'monthly')", name='chk_managed_accounts_period_type'),
    sa.CheckConstraint('`initial_capital` >= 0 AND `high_water_mark` >= 0', name='chk_managed_accounts_capital'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], name='fk_managed_accounts_account'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_managed_accounts_bot'),
    sa.ForeignKeyConstraint(['investor_id'], ['investors.id'], name='fk_managed_accounts_investor'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_managed_accounts_account', 'managed_accounts', ['account_id'], unique=False)
    op.create_index('idx_managed_accounts_active', 'managed_accounts', ['is_active'], unique=False)
    op.create_index('idx_managed_accounts_bot', 'managed_accounts', ['bot_id'], unique=False)
    op.create_index('idx_managed_accounts_investor', 'managed_accounts', ['investor_id'], unique=False)
    op.create_table('portfolio_snapshots',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('equity', sa.DECIMAL(precision=30, scale=12), nullable=False),
    sa.Column('cash', sa.DECIMAL(precision=30, scale=12), nullable=False),
    sa.Column('unrealized_pnl', sa.DECIMAL(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('realized_pnl', sa.DECIMAL(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.CheckConstraint('`equity` >= 0 AND `cash` >= 0', name='chk_snapshots_money'),
    sa.CheckConstraint('json_valid(`meta`)', name='chk_snapshots_meta_json'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_snapshots_bot'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_snapshots_bot_ts', 'portfolio_snapshots', ['bot_id', 'ts'], unique=False)
    op.create_table('positions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('symbol_id', sa.BigInteger(), nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('avg_price', sa.NUMERIC(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('realized_pnl', sa.NUMERIC(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('updated_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('`avg_price` >= 0', name='chk_positions_prices'),
    sa.CheckConstraint('`qty` >= 0', name='chk_positions_qty'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_positions_bot'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name='fk_positions_symbol'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'symbol_id', name='uq_positions_bot_symbol'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_positions_bot', 'positions', ['bot_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('model_id', sa.BigInteger(), nullable=True),
    sa.Column('symbol_id', sa.BigInteger(), nullable=False),
    sa.Column('timeframe_id', sa.SmallInteger(), nullable=False),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), nullable=False),
    sa.Column('score', sa.DECIMAL(precision=12, scale=8), nullable=True),
    sa.Column('raw_output', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('json_valid(`raw_output`)', name='chk_predictions_raw_output_json'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_predictions_bot', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], name='fk_predictions_model'),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], name='fk_predictions_symbol'),
    sa.ForeignKeyConstraint(['timeframe_id'], ['timeframes.id'], name='fk_predictions_timeframe'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bot_id', 'model_id', 'symbol_id', 'timeframe_id', 'ts', name='uq_predictions'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_predictions_bot_ts', 'predictions', ['bot_id', 'ts'], unique=False)
    op.create_index('idx_predictions_symbol_tf_ts', 'predictions', ['symbol_id', 'timeframe_id', 'ts'], unique=False)
    op.create_table('signals',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), nullable=False),
    sa.Column('action', sa.String(length=8), nullable=False),
    sa.Column('entry_price', sa.DECIMAL(precision=30, scale=12), nullable=True, comment='Precio de entrada sugerido por el agente'),
    sa.Column('stop_loss', sa.DECIMAL(precision=30, scale=12), nullable=True, comment='Nivel de stop loss calculado'),
    sa.Column('take_profit', sa.DECIMAL(precision=30, scale=12), nullable=True, comment='Nivel de take profit calculado'),
    sa.Column('position_size', sa.DECIMAL(precision=30, scale=12), nullable=True, comment='Tamaño de posición: capital × risk_pct / |entry-SL|'),
    sa.Column('rr_ratio', sa.DECIMAL(precision=10, scale=4), nullable=True, comment='Ratio Riesgo/Recompensa (TP-entry)/(entry-SL)'),
    sa.Column('approved', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), nullable=False, comment='1=aprobada por todos los filtros, 0=rechazada'),
    sa.Column('confidence', sa.DECIMAL(precision=6, scale=5), nullable=True),
    sa.Column('model_version', sa.String(length=64), nullable=True),
    sa.Column('features_hash', sa.String(length=128), nullable=True),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`action` IN ('buy', 'sell', 'hold')", name='chk_signals_action'),
    sa.CheckConstraint('`confidence` IS NULL OR (`confidence` >= 0 AND `confidence` <= 1)', name='chk_signals_confidence'),
    sa.CheckConstraint('json_valid(`reasons`)', name='chk_signals_reasons_json'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_signals_bot'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_signals_bot_ts', 'signals', ['bot_id', 'ts'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('alert_rule_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_id', sa.BigInteger(), nullable=True),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('severity', sa.String(length=16), server_default=sa.text("'info'"), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('delivery_status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.CheckConstraint("`delivery_status` IN ('pending', 'sent', 'failed')", name='chk_alert_events_delivery'),
    sa.CheckConstraint("`severity` IN ('info', 'warning', 'critical')", name='chk_alert_events_severity'),
    sa.CheckConstraint('json_valid(`payload`)', name='chk_alert_events_payload_json'),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name='fk_alert_events_rule', ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_alert_events_bot'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_alert_events_user'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_alert_events_bot_ts', 'alert_events', ['bot_id', 'ts'], unique=False)
    op.create_index('idx_alert_events_delivery_ts', 'alert_events', ['delivery_status', 'ts'], unique=False)
    op.create_index('idx_alert_events_ts', 'alert_events', ['ts'], unique=False)
    op.create_index('idx_alert_events_user_ts', 'alert_events', ['user_id', 'ts'], unique=False)
    op.create_table('billing_periods',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('managed_account_id', sa.BigInteger(), nullable=False),
    sa.Column('start_ts', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('end_ts', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('opening_equity', sa.Numeric(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('closing_equity', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('gross_pnl', sa.Numeric(precision=30, scale=12), nullable=True, comment='closing_equity - MAX(opening_equity, HWM)'),
    sa.Column('fee_pct', sa.Numeric(precision=5, scale=4), server_default=sa.text("'0.0000'"), nullable=False, comment='Snapshot del fee_pct al abrir el período'),
    sa.Column('fee_amount', sa.Numeric(precision=30, scale=12), nullable=True),
    sa.Column('net_pnl', sa.Numeric(precision=30, scale=12), nullable=True, comment='gross_pnl - fee_amount'),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('closed_at', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.CheckConstraint("`status` IN ('open', 'closed')", name='chk_billing_periods_status'),
    sa.CheckConstraint('`opening_equity` >= 0', name='chk_billing_periods_equity'),
    sa.ForeignKeyConstraint(['managed_account_id'], ['managed_accounts.id'], name='fk_billing_periods_managed_account'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_billing_periods_managed_account', 'billing_periods', ['managed_account_id'], unique=False)
    op.create_index('idx_billing_periods_start_ts', 'billing_periods', ['managed_account_id', 'start_ts'], unique=False)
    op.create_index('idx_billing_periods_status', 'billing_periods', ['status'], unique=False)
    op.create_table('orders',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('bot_id', sa.BigInteger(), nullable=False),
    sa.Column('signal_id', sa.BigInteger(), nullable=True),
    sa.Column('exchange_order_id', sa.String(length=128), nullable=True),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('side', sa.String(length=8), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=20), server_default=sa.text("'new'"), nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=30, scale=12), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=30, scale=12), nullable=True),
    sa.Column('stop_price', sa.NUMERIC(precision=30, scale=12), nullable=True),
    sa.Column('time_in_force', sa.String(length=8), nullable=True),
    sa.Column('meta', sa.JSON(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("(`type` = 'market' AND `price` IS NULL AND `stop_price` IS NULL) OR (`type` = 'limit' AND `price` IS NOT NULL AND `stop_price` IS NULL) OR (`type` IN ('stop', 'stop_limit') AND `stop_price` IS NOT NULL)", name='chk_orders_price_logic'),
    sa.CheckConstraint("`side` IN ('buy', 'sell')", name='chk_orders_side'),
    sa.CheckConstraint("`status` IN ('new', 'sent', 'partially_filled', 'filled', 'canceled', 'rejected')", name='chk_orders_status'),
    sa.CheckConstraint("`type` IN ('market', 'limit', 'stop', 'stop_limit')", name='chk_orders_type'),
    sa.CheckConstraint('`qty` > 0', name='chk_orders_qty'),
    sa.CheckConstraint('json_valid(`meta`)', name='chk_orders_meta_json'),
    sa.ForeignKeyConstraint(['bot_id'], ['bots.id'], name='fk_orders_bot'),
    sa.ForeignKeyConstraint(['signal_id'], ['signals.id'], name='fk_orders_signal'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_orders_bot_ts', 'orders', ['bot_id', 'ts'], unique=False)
    op.create_index('idx_orders_exchange_order_id', 'orders', ['exchange_order_id'], unique=False)
    op.create_index('idx_orders_signal', 'orders', ['signal_id'], unique=False)
    op.create_index('idx_orders_status', 'orders', ['status'], unique=False)
    op.create_table('fee_transactions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('billing_period_id', sa.BigInteger(), nullable=False),
    sa.Column('managed_account_id', sa.BigInteger(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'pending'"), nullable=False),
    sa.Column('charged_at', mysql.TIMESTAMP(fsp=6), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint("`status` IN ('pending', 'charged', 'waived')", name='chk_fee_transactions_status'),
    sa.CheckConstraint('`amount` >= 0', name='chk_fee_transactions_amount'),
    sa.ForeignKeyConstraint(['billing_period_id'], ['billing_periods.id'], name='fk_fee_transactions_billing_period'),
    sa.ForeignKeyConstraint(['managed_account_id'], ['managed_accounts.id'], name='fk_fee_transactions_managed_account'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('billing_period_id', name='uq_fee_transactions_period'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fee_transactions_managed_account', 'fee_transactions', ['managed_account_id'], unique=False)
    op.create_index('idx_fee_transactions_status', 'fee_transactions', ['status'], unique=False)
    op.create_table('fills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('exchange_trade_id', sa.String(length=128), nullable=True),
    sa.Column('ts', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.Column('qty', sa.NUMERIC(precision=30, scale=12), nullable=False),
    sa.Column('price', sa.NUMERIC(precision=30, scale=12), nullable=False),
    sa.Column('fee', sa.NUMERIC(precision=30, scale=12), server_default=sa.text("'0.000000000000'"), nullable=False),
    sa.Column('fee_asset', sa.String(length=32), nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(fsp=6), server_default=sa.text('CURRENT_TIMESTAMP(6)'), nullable=False),
    sa.CheckConstraint('`qty` > 0 AND `price` >= 0 AND `fee` >= 0', name='chk_fills_qty_price'),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name='fk_fills_order', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_charset='utf8mb4',
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_engine='InnoDB'
    )
    op.create_index('idx_fills_exchange_trade_id', 'fills', ['exchange_trade_id'], unique=False)
    op.create_index('idx_fills_order_ts', 'fills', ['order_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_fills_order_ts', table_name='fills')
    op.drop_index('idx_fills_exchange_trade_id', table_name='fills')
    op.drop_table('fills')
    op.drop_index('idx_fee_transactions_status', table_name='fee_transactions')
    op.drop_index('idx_fee_transactions_managed_account', table_name='fee_transactions')
    op.drop_table('fee_transactions')
    op.drop_index('idx_orders_status', table_name='orders')
    op.drop_index('idx_orders_signal', table_name='orders')
    op.drop_index('idx_orders_exchange_order_id', table_name='orders')
    op.drop_index('idx_orders_bot_ts', table_name='orders')
    op.drop_table('orders')
    op.drop_index('idx_billing_periods_status', table_name='billing_periods')
    op.drop_index('idx_billing_periods_start_ts', table_name='billing_periods')
    op.drop_index('idx_billing_periods_managed_account', table_name='billing_periods')
    op.drop_table('billing_periods')
    op.drop_index('idx_alert_events_user_ts', table_name='alert_events')
    op.drop_index('idx_alert_events_ts', table_name='alert_events')
    op.drop_index('idx_alert_events_delivery_ts', table_name='alert_events')
    op.drop_index('idx_alert_events_bot_ts', table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index('idx_signals_bot_ts', table_name='signals')
    op.drop_table('signals')
    op.drop_index('idx_predictions_symbol_tf_ts', table_name='predictions')
    op.drop_index('idx_predictions_bot_ts', table_name='predictions')
    op.drop_table('predictions')
    op.drop_index('idx_positions_bot', table_name='positions')
    op.drop_table('positions')
    op.drop_index('idx_snapshots_bot_ts', table_name='portfolio_snapshots')
    op.drop_table('portfolio_snapshots')
    op.drop_index('idx_managed_accounts_investor', table_name='managed_accounts')
    op.drop_index('idx_managed_accounts_bot', table_name='managed_accounts')
    op.drop_index('idx_managed_accounts_active', table_name='managed_accounts')
    op.drop_index('idx_managed_accounts_account', table_name='managed_accounts')
    op.drop_table('managed_accounts')
    op.drop_index('idx_audit_logs_user_ts', table_name='audit_logs')
    op.drop_index('idx_audit_logs_ts', table_name='audit_logs')
    op.drop_index('idx_audit_logs_bot_ts', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('idx_alert_rules_user', table_name='alert_rules')
    op.drop_index('idx_alert_rules_bot', table_name='alert_rules')
    op.drop_table('alert_rules')
    op.drop_index('idx_model_runs_model', table_name='model_runs')
    op.drop_index('idx_model_runs_dataset', table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index('idx_bots_symbol', table_name='bots')
    op.drop_index('idx_bots_strategy', table_name='bots')
    op.drop_index('idx_bots_status', table_name='bots')
    op.drop_index('idx_bots_feature_set', table_name='bots')
    op.drop_index('idx_bots_account', table_name='bots')
    op.drop_table('bots')
    op.drop_index('idx_balances_account_ts', table_name='account_balances')
    op.drop_table('account_balances')
    op.drop_index('idx_investors_active', table_name='investors')
    op.drop_table('investors')
    op.drop_index('idx_datasets_symbol_tf', table_name='datasets')
    op.drop_table('datasets')
    op.drop_index('idx_candles_symbol_tf_ts', table_name='candles')
    op.drop_table('candles')
    op.drop_index('idx_candle_features_lookup', table_name='candle_features')
    op.drop_table('candle_features')
    op.drop_index('idx_accounts_user', table_name='accounts')
    op.drop_index('idx_accounts_mode', table_name='accounts')
    op.drop_index('idx_accounts_exchange', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('idx_users_token_jti', table_name='users')
    op.drop_index('idx_users_status', table_name='users')
    op.drop_index('idx_users_role_id', table_name='users')
    op.drop_index('idx_users_otp_expires', table_name='users')
    op.drop_index('idx_users_login_locked_until', table_name='users')
    op.drop_table('users')
    op.drop_index('idx_symbols_exchange', table_name='symbols')
    op.drop_index('idx_symbols_asset_class', table_name='symbols')
    op.drop_table('symbols')
    op.drop_index('idx_models_status', table_name='models')
    op.drop_index('idx_models_feature_set', table_name='models')
    op.drop_table('models')
    op.drop_table('timeframes')
    op.drop_index('idx_system_events_ts', table_name='system_events')
    op.drop_index('idx_system_events_component_ts', table_name='system_events')
    op.drop_table('system_events')
    op.drop_table('strategies')
    op.drop_table('roles')
    op.drop_table('feature_sets')
    op.drop_table('exchanges')
    # ### end Alembic commands ###
