/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminAdminIndexRouteImport } from './routes/_admin.admin/index'

const AuthLoginLazyRouteImport = createFileRoute('/_auth/login')()
const AdminAdminSecurityLazyRouteImport = createFileRoute(
  '/_admin/admin/security',
)()
const AdminAdminRolesLazyRouteImport = createFileRoute('/_admin/admin/roles')()
const AdminAdminProfileLazyRouteImport = createFileRoute(
  '/_admin/admin/profile',
)()
const AdminAdminDashboardLazyRouteImport = createFileRoute(
  '/_admin/admin/dashboard',
)()
const AdminAdminVehiclesIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/vehicles/',
)()
const AdminAdminUsersIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/users/',
)()
const AdminAdminPetsIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/pets/',
)()
const AdminAdminLocationsIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/locations/',
)()
const AdminAdminCustomersIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/customers/',
)()
const AdminAdminVehiclesCreateLazyRouteImport = createFileRoute(
  '/_admin/admin/vehicles/create',
)()
const AdminAdminUsersCreateLazyRouteImport = createFileRoute(
  '/_admin/admin/users/create',
)()
const AdminAdminPetsCreateLazyRouteImport = createFileRoute(
  '/_admin/admin/pets/create',
)()
const AdminAdminLocationsLocationIdLazyRouteImport = createFileRoute(
  '/_admin/admin/locations/$locationId',
)()
const AdminAdminInventoryQuickExitLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/quick-exit',
)()
const AdminAdminCustomersCreateLazyRouteImport = createFileRoute(
  '/_admin/admin/customers/create',
)()
const AdminAdminServicesPetIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/services/pet/',
)()
const AdminAdminServicesAutoIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/services/auto/',
)()
const AdminAdminInventoryTransfersIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/transfers/',
)()
const AdminAdminInventorySuppliersIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/suppliers/',
)()
const AdminAdminInventoryPanelIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/panel/',
)()
const AdminAdminInventoryItemsIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/items/',
)()
const AdminAdminInventoryDocumentsIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/documents/',
)()
const AdminAdminInventoryCountsIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/counts/',
)()
const AdminAdminInventoryCatalogsIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/catalogs/',
)()
const AdminAdminCatalogsVehiclesIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/catalogs/vehicles/',
)()
const AdminAdminCatalogsBreedsIndexLazyRouteImport = createFileRoute(
  '/_admin/admin/catalogs/breeds/',
)()
const AdminAdminVehiclesEditVehicleIdLazyRouteImport = createFileRoute(
  '/_admin/admin/vehicles/edit/$vehicleId',
)()
const AdminAdminUsersEditUserIdLazyRouteImport = createFileRoute(
  '/_admin/admin/users/edit/$userId',
)()
const AdminAdminServicesPetCreateLazyRouteImport = createFileRoute(
  '/_admin/admin/services/pet/create',
)()
const AdminAdminServicesAutoCreateLazyRouteImport = createFileRoute(
  '/_admin/admin/services/auto/create',
)()
const AdminAdminPetsEditPetIdLazyRouteImport = createFileRoute(
  '/_admin/admin/pets/edit/$petId',
)()
const AdminAdminInventoryTransfersCreateLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/transfers/create',
)()
const AdminAdminInventoryTransfersTransferIdLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/transfers/$transferId',
)()
const AdminAdminInventoryItemsCreateLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/items/create',
)()
const AdminAdminInventoryDocumentsExitLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/documents/exit',
)()
const AdminAdminInventoryDocumentsEntryLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/documents/entry',
)()
const AdminAdminInventoryDocumentsDocumentIdLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/documents/$documentId',
)()
const AdminAdminInventoryCountsCountIdLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/counts/$countId',
)()
const AdminAdminCustomersEditCustomerIdLazyRouteImport = createFileRoute(
  '/_admin/admin/customers/edit/$customerId',
)()
const AdminAdminCatalogsVehiclesMakeIdLazyRouteImport = createFileRoute(
  '/_admin/admin/catalogs/vehicles/$makeId',
)()
const AdminAdminServicesPetEditServiceIdLazyRouteImport = createFileRoute(
  '/_admin/admin/services/pet/edit/$serviceId',
)()
const AdminAdminServicesAutoEditServiceIdLazyRouteImport = createFileRoute(
  '/_admin/admin/services/auto/edit/$serviceId',
)()
const AdminAdminInventoryItemsEditItemIdLazyRouteImport = createFileRoute(
  '/_admin/admin/inventory/items/edit/$itemId',
)()

const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginLazyRoute = AuthLoginLazyRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRoute,
} as any).lazy(() => import('./routes/_auth/login.lazy').then((d) => d.Route))
const AdminAdminIndexRoute = AdminAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAdminSecurityLazyRoute = AdminAdminSecurityLazyRouteImport.update({
  id: '/admin/security',
  path: '/admin/security',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/_admin.admin/security.lazy').then((d) => d.Route),
)
const AdminAdminRolesLazyRoute = AdminAdminRolesLazyRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/_admin.admin/roles.lazy').then((d) => d.Route),
)
const AdminAdminProfileLazyRoute = AdminAdminProfileLazyRouteImport.update({
  id: '/admin/profile',
  path: '/admin/profile',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/_admin.admin/profile.lazy').then((d) => d.Route),
)
const AdminAdminDashboardLazyRoute = AdminAdminDashboardLazyRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/_admin.admin/dashboard.lazy').then((d) => d.Route),
)
const AdminAdminVehiclesIndexLazyRoute =
  AdminAdminVehiclesIndexLazyRouteImport.update({
    id: '/admin/vehicles/',
    path: '/admin/vehicles/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/vehicles/index.lazy').then((d) => d.Route),
  )
const AdminAdminUsersIndexLazyRoute =
  AdminAdminUsersIndexLazyRouteImport.update({
    id: '/admin/users/',
    path: '/admin/users/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/users/index.lazy').then((d) => d.Route),
  )
const AdminAdminPetsIndexLazyRoute = AdminAdminPetsIndexLazyRouteImport.update({
  id: '/admin/pets/',
  path: '/admin/pets/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/_admin.admin/pets/index.lazy').then((d) => d.Route),
)
const AdminAdminLocationsIndexLazyRoute =
  AdminAdminLocationsIndexLazyRouteImport.update({
    id: '/admin/locations/',
    path: '/admin/locations/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/locations/index.lazy').then((d) => d.Route),
  )
const AdminAdminCustomersIndexLazyRoute =
  AdminAdminCustomersIndexLazyRouteImport.update({
    id: '/admin/customers/',
    path: '/admin/customers/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/customers/index.lazy').then((d) => d.Route),
  )
const AdminAdminVehiclesCreateLazyRoute =
  AdminAdminVehiclesCreateLazyRouteImport.update({
    id: '/admin/vehicles/create',
    path: '/admin/vehicles/create',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/vehicles/create.lazy').then((d) => d.Route),
  )
const AdminAdminUsersCreateLazyRoute =
  AdminAdminUsersCreateLazyRouteImport.update({
    id: '/admin/users/create',
    path: '/admin/users/create',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/users/create.lazy').then((d) => d.Route),
  )
const AdminAdminPetsCreateLazyRoute =
  AdminAdminPetsCreateLazyRouteImport.update({
    id: '/admin/pets/create',
    path: '/admin/pets/create',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/pets/create.lazy').then((d) => d.Route),
  )
const AdminAdminLocationsLocationIdLazyRoute =
  AdminAdminLocationsLocationIdLazyRouteImport.update({
    id: '/admin/locations/$locationId',
    path: '/admin/locations/$locationId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/locations/$locationId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryQuickExitLazyRoute =
  AdminAdminInventoryQuickExitLazyRouteImport.update({
    id: '/admin/inventory/quick-exit',
    path: '/admin/inventory/quick-exit',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/quick-exit.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminCustomersCreateLazyRoute =
  AdminAdminCustomersCreateLazyRouteImport.update({
    id: '/admin/customers/create',
    path: '/admin/customers/create',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/customers/create.lazy').then((d) => d.Route),
  )
const AdminAdminServicesPetIndexLazyRoute =
  AdminAdminServicesPetIndexLazyRouteImport.update({
    id: '/admin/services/pet/',
    path: '/admin/services/pet/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/services/pet/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminServicesAutoIndexLazyRoute =
  AdminAdminServicesAutoIndexLazyRouteImport.update({
    id: '/admin/services/auto/',
    path: '/admin/services/auto/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/services/auto/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryTransfersIndexLazyRoute =
  AdminAdminInventoryTransfersIndexLazyRouteImport.update({
    id: '/admin/inventory/transfers/',
    path: '/admin/inventory/transfers/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/transfers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventorySuppliersIndexLazyRoute =
  AdminAdminInventorySuppliersIndexLazyRouteImport.update({
    id: '/admin/inventory/suppliers/',
    path: '/admin/inventory/suppliers/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/suppliers/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryPanelIndexLazyRoute =
  AdminAdminInventoryPanelIndexLazyRouteImport.update({
    id: '/admin/inventory/panel/',
    path: '/admin/inventory/panel/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/panel/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryItemsIndexLazyRoute =
  AdminAdminInventoryItemsIndexLazyRouteImport.update({
    id: '/admin/inventory/items/',
    path: '/admin/inventory/items/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/items/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryDocumentsIndexLazyRoute =
  AdminAdminInventoryDocumentsIndexLazyRouteImport.update({
    id: '/admin/inventory/documents/',
    path: '/admin/inventory/documents/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/documents/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryCountsIndexLazyRoute =
  AdminAdminInventoryCountsIndexLazyRouteImport.update({
    id: '/admin/inventory/counts/',
    path: '/admin/inventory/counts/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/counts/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryCatalogsIndexLazyRoute =
  AdminAdminInventoryCatalogsIndexLazyRouteImport.update({
    id: '/admin/inventory/catalogs/',
    path: '/admin/inventory/catalogs/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/catalogs/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminCatalogsVehiclesIndexLazyRoute =
  AdminAdminCatalogsVehiclesIndexLazyRouteImport.update({
    id: '/admin/catalogs/vehicles/',
    path: '/admin/catalogs/vehicles/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/catalogs/vehicles/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminCatalogsBreedsIndexLazyRoute =
  AdminAdminCatalogsBreedsIndexLazyRouteImport.update({
    id: '/admin/catalogs/breeds/',
    path: '/admin/catalogs/breeds/',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/catalogs/breeds/index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminVehiclesEditVehicleIdLazyRoute =
  AdminAdminVehiclesEditVehicleIdLazyRouteImport.update({
    id: '/admin/vehicles/edit/$vehicleId',
    path: '/admin/vehicles/edit/$vehicleId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/vehicles/edit/$vehicleId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminUsersEditUserIdLazyRoute =
  AdminAdminUsersEditUserIdLazyRouteImport.update({
    id: '/admin/users/edit/$userId',
    path: '/admin/users/edit/$userId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/users/edit/$userId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminServicesPetCreateLazyRoute =
  AdminAdminServicesPetCreateLazyRouteImport.update({
    id: '/admin/services/pet/create',
    path: '/admin/services/pet/create',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/services/pet/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminServicesAutoCreateLazyRoute =
  AdminAdminServicesAutoCreateLazyRouteImport.update({
    id: '/admin/services/auto/create',
    path: '/admin/services/auto/create',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/services/auto/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminPetsEditPetIdLazyRoute =
  AdminAdminPetsEditPetIdLazyRouteImport.update({
    id: '/admin/pets/edit/$petId',
    path: '/admin/pets/edit/$petId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/pets/edit/$petId.lazy').then((d) => d.Route),
  )
const AdminAdminInventoryTransfersCreateLazyRoute =
  AdminAdminInventoryTransfersCreateLazyRouteImport.update({
    id: '/admin/inventory/transfers/create',
    path: '/admin/inventory/transfers/create',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/transfers/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryTransfersTransferIdLazyRoute =
  AdminAdminInventoryTransfersTransferIdLazyRouteImport.update({
    id: '/admin/inventory/transfers/$transferId',
    path: '/admin/inventory/transfers/$transferId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/transfers/$transferId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryItemsCreateLazyRoute =
  AdminAdminInventoryItemsCreateLazyRouteImport.update({
    id: '/admin/inventory/items/create',
    path: '/admin/inventory/items/create',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/items/create.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryDocumentsExitLazyRoute =
  AdminAdminInventoryDocumentsExitLazyRouteImport.update({
    id: '/admin/inventory/documents/exit',
    path: '/admin/inventory/documents/exit',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/documents/exit.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryDocumentsEntryLazyRoute =
  AdminAdminInventoryDocumentsEntryLazyRouteImport.update({
    id: '/admin/inventory/documents/entry',
    path: '/admin/inventory/documents/entry',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/documents/entry.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryDocumentsDocumentIdLazyRoute =
  AdminAdminInventoryDocumentsDocumentIdLazyRouteImport.update({
    id: '/admin/inventory/documents/$documentId',
    path: '/admin/inventory/documents/$documentId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/documents/$documentId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryCountsCountIdLazyRoute =
  AdminAdminInventoryCountsCountIdLazyRouteImport.update({
    id: '/admin/inventory/counts/$countId',
    path: '/admin/inventory/counts/$countId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/counts/$countId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminCustomersEditCustomerIdLazyRoute =
  AdminAdminCustomersEditCustomerIdLazyRouteImport.update({
    id: '/admin/customers/edit/$customerId',
    path: '/admin/customers/edit/$customerId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/customers/edit/$customerId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminCatalogsVehiclesMakeIdLazyRoute =
  AdminAdminCatalogsVehiclesMakeIdLazyRouteImport.update({
    id: '/admin/catalogs/vehicles/$makeId',
    path: '/admin/catalogs/vehicles/$makeId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/catalogs/vehicles/$makeId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminServicesPetEditServiceIdLazyRoute =
  AdminAdminServicesPetEditServiceIdLazyRouteImport.update({
    id: '/admin/services/pet/edit/$serviceId',
    path: '/admin/services/pet/edit/$serviceId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/services/pet/edit/$serviceId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminServicesAutoEditServiceIdLazyRoute =
  AdminAdminServicesAutoEditServiceIdLazyRouteImport.update({
    id: '/admin/services/auto/edit/$serviceId',
    path: '/admin/services/auto/edit/$serviceId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/services/auto/edit/$serviceId.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminAdminInventoryItemsEditItemIdLazyRoute =
  AdminAdminInventoryItemsEditItemIdLazyRouteImport.update({
    id: '/admin/inventory/items/edit/$itemId',
    path: '/admin/inventory/items/edit/$itemId',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/_admin.admin/inventory/items/edit/$itemId.lazy').then(
      (d) => d.Route,
    ),
  )

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginLazyRoute
  '/admin/dashboard': typeof AdminAdminDashboardLazyRoute
  '/admin/profile': typeof AdminAdminProfileLazyRoute
  '/admin/roles': typeof AdminAdminRolesLazyRoute
  '/admin/security': typeof AdminAdminSecurityLazyRoute
  '/admin/': typeof AdminAdminIndexRoute
  '/admin/customers/create': typeof AdminAdminCustomersCreateLazyRoute
  '/admin/inventory/quick-exit': typeof AdminAdminInventoryQuickExitLazyRoute
  '/admin/locations/$locationId': typeof AdminAdminLocationsLocationIdLazyRoute
  '/admin/pets/create': typeof AdminAdminPetsCreateLazyRoute
  '/admin/users/create': typeof AdminAdminUsersCreateLazyRoute
  '/admin/vehicles/create': typeof AdminAdminVehiclesCreateLazyRoute
  '/admin/customers/': typeof AdminAdminCustomersIndexLazyRoute
  '/admin/locations/': typeof AdminAdminLocationsIndexLazyRoute
  '/admin/pets/': typeof AdminAdminPetsIndexLazyRoute
  '/admin/users/': typeof AdminAdminUsersIndexLazyRoute
  '/admin/vehicles/': typeof AdminAdminVehiclesIndexLazyRoute
  '/admin/catalogs/vehicles/$makeId': typeof AdminAdminCatalogsVehiclesMakeIdLazyRoute
  '/admin/customers/edit/$customerId': typeof AdminAdminCustomersEditCustomerIdLazyRoute
  '/admin/inventory/counts/$countId': typeof AdminAdminInventoryCountsCountIdLazyRoute
  '/admin/inventory/documents/$documentId': typeof AdminAdminInventoryDocumentsDocumentIdLazyRoute
  '/admin/inventory/documents/entry': typeof AdminAdminInventoryDocumentsEntryLazyRoute
  '/admin/inventory/documents/exit': typeof AdminAdminInventoryDocumentsExitLazyRoute
  '/admin/inventory/items/create': typeof AdminAdminInventoryItemsCreateLazyRoute
  '/admin/inventory/transfers/$transferId': typeof AdminAdminInventoryTransfersTransferIdLazyRoute
  '/admin/inventory/transfers/create': typeof AdminAdminInventoryTransfersCreateLazyRoute
  '/admin/pets/edit/$petId': typeof AdminAdminPetsEditPetIdLazyRoute
  '/admin/services/auto/create': typeof AdminAdminServicesAutoCreateLazyRoute
  '/admin/services/pet/create': typeof AdminAdminServicesPetCreateLazyRoute
  '/admin/users/edit/$userId': typeof AdminAdminUsersEditUserIdLazyRoute
  '/admin/vehicles/edit/$vehicleId': typeof AdminAdminVehiclesEditVehicleIdLazyRoute
  '/admin/catalogs/breeds/': typeof AdminAdminCatalogsBreedsIndexLazyRoute
  '/admin/catalogs/vehicles/': typeof AdminAdminCatalogsVehiclesIndexLazyRoute
  '/admin/inventory/catalogs/': typeof AdminAdminInventoryCatalogsIndexLazyRoute
  '/admin/inventory/counts/': typeof AdminAdminInventoryCountsIndexLazyRoute
  '/admin/inventory/documents/': typeof AdminAdminInventoryDocumentsIndexLazyRoute
  '/admin/inventory/items/': typeof AdminAdminInventoryItemsIndexLazyRoute
  '/admin/inventory/panel/': typeof AdminAdminInventoryPanelIndexLazyRoute
  '/admin/inventory/suppliers/': typeof AdminAdminInventorySuppliersIndexLazyRoute
  '/admin/inventory/transfers/': typeof AdminAdminInventoryTransfersIndexLazyRoute
  '/admin/services/auto/': typeof AdminAdminServicesAutoIndexLazyRoute
  '/admin/services/pet/': typeof AdminAdminServicesPetIndexLazyRoute
  '/admin/inventory/items/edit/$itemId': typeof AdminAdminInventoryItemsEditItemIdLazyRoute
  '/admin/services/auto/edit/$serviceId': typeof AdminAdminServicesAutoEditServiceIdLazyRoute
  '/admin/services/pet/edit/$serviceId': typeof AdminAdminServicesPetEditServiceIdLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof AuthLoginLazyRoute
  '/admin/dashboard': typeof AdminAdminDashboardLazyRoute
  '/admin/profile': typeof AdminAdminProfileLazyRoute
  '/admin/roles': typeof AdminAdminRolesLazyRoute
  '/admin/security': typeof AdminAdminSecurityLazyRoute
  '/admin': typeof AdminAdminIndexRoute
  '/admin/customers/create': typeof AdminAdminCustomersCreateLazyRoute
  '/admin/inventory/quick-exit': typeof AdminAdminInventoryQuickExitLazyRoute
  '/admin/locations/$locationId': typeof AdminAdminLocationsLocationIdLazyRoute
  '/admin/pets/create': typeof AdminAdminPetsCreateLazyRoute
  '/admin/users/create': typeof AdminAdminUsersCreateLazyRoute
  '/admin/vehicles/create': typeof AdminAdminVehiclesCreateLazyRoute
  '/admin/customers': typeof AdminAdminCustomersIndexLazyRoute
  '/admin/locations': typeof AdminAdminLocationsIndexLazyRoute
  '/admin/pets': typeof AdminAdminPetsIndexLazyRoute
  '/admin/users': typeof AdminAdminUsersIndexLazyRoute
  '/admin/vehicles': typeof AdminAdminVehiclesIndexLazyRoute
  '/admin/catalogs/vehicles/$makeId': typeof AdminAdminCatalogsVehiclesMakeIdLazyRoute
  '/admin/customers/edit/$customerId': typeof AdminAdminCustomersEditCustomerIdLazyRoute
  '/admin/inventory/counts/$countId': typeof AdminAdminInventoryCountsCountIdLazyRoute
  '/admin/inventory/documents/$documentId': typeof AdminAdminInventoryDocumentsDocumentIdLazyRoute
  '/admin/inventory/documents/entry': typeof AdminAdminInventoryDocumentsEntryLazyRoute
  '/admin/inventory/documents/exit': typeof AdminAdminInventoryDocumentsExitLazyRoute
  '/admin/inventory/items/create': typeof AdminAdminInventoryItemsCreateLazyRoute
  '/admin/inventory/transfers/$transferId': typeof AdminAdminInventoryTransfersTransferIdLazyRoute
  '/admin/inventory/transfers/create': typeof AdminAdminInventoryTransfersCreateLazyRoute
  '/admin/pets/edit/$petId': typeof AdminAdminPetsEditPetIdLazyRoute
  '/admin/services/auto/create': typeof AdminAdminServicesAutoCreateLazyRoute
  '/admin/services/pet/create': typeof AdminAdminServicesPetCreateLazyRoute
  '/admin/users/edit/$userId': typeof AdminAdminUsersEditUserIdLazyRoute
  '/admin/vehicles/edit/$vehicleId': typeof AdminAdminVehiclesEditVehicleIdLazyRoute
  '/admin/catalogs/breeds': typeof AdminAdminCatalogsBreedsIndexLazyRoute
  '/admin/catalogs/vehicles': typeof AdminAdminCatalogsVehiclesIndexLazyRoute
  '/admin/inventory/catalogs': typeof AdminAdminInventoryCatalogsIndexLazyRoute
  '/admin/inventory/counts': typeof AdminAdminInventoryCountsIndexLazyRoute
  '/admin/inventory/documents': typeof AdminAdminInventoryDocumentsIndexLazyRoute
  '/admin/inventory/items': typeof AdminAdminInventoryItemsIndexLazyRoute
  '/admin/inventory/panel': typeof AdminAdminInventoryPanelIndexLazyRoute
  '/admin/inventory/suppliers': typeof AdminAdminInventorySuppliersIndexLazyRoute
  '/admin/inventory/transfers': typeof AdminAdminInventoryTransfersIndexLazyRoute
  '/admin/services/auto': typeof AdminAdminServicesAutoIndexLazyRoute
  '/admin/services/pet': typeof AdminAdminServicesPetIndexLazyRoute
  '/admin/inventory/items/edit/$itemId': typeof AdminAdminInventoryItemsEditItemIdLazyRoute
  '/admin/services/auto/edit/$serviceId': typeof AdminAdminServicesAutoEditServiceIdLazyRoute
  '/admin/services/pet/edit/$serviceId': typeof AdminAdminServicesPetEditServiceIdLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_admin': typeof AdminRouteWithChildren
  '/_auth': typeof AuthRouteWithChildren
  '/_auth/login': typeof AuthLoginLazyRoute
  '/_admin/admin/dashboard': typeof AdminAdminDashboardLazyRoute
  '/_admin/admin/profile': typeof AdminAdminProfileLazyRoute
  '/_admin/admin/roles': typeof AdminAdminRolesLazyRoute
  '/_admin/admin/security': typeof AdminAdminSecurityLazyRoute
  '/_admin/admin/': typeof AdminAdminIndexRoute
  '/_admin/admin/customers/create': typeof AdminAdminCustomersCreateLazyRoute
  '/_admin/admin/inventory/quick-exit': typeof AdminAdminInventoryQuickExitLazyRoute
  '/_admin/admin/locations/$locationId': typeof AdminAdminLocationsLocationIdLazyRoute
  '/_admin/admin/pets/create': typeof AdminAdminPetsCreateLazyRoute
  '/_admin/admin/users/create': typeof AdminAdminUsersCreateLazyRoute
  '/_admin/admin/vehicles/create': typeof AdminAdminVehiclesCreateLazyRoute
  '/_admin/admin/customers/': typeof AdminAdminCustomersIndexLazyRoute
  '/_admin/admin/locations/': typeof AdminAdminLocationsIndexLazyRoute
  '/_admin/admin/pets/': typeof AdminAdminPetsIndexLazyRoute
  '/_admin/admin/users/': typeof AdminAdminUsersIndexLazyRoute
  '/_admin/admin/vehicles/': typeof AdminAdminVehiclesIndexLazyRoute
  '/_admin/admin/catalogs/vehicles/$makeId': typeof AdminAdminCatalogsVehiclesMakeIdLazyRoute
  '/_admin/admin/customers/edit/$customerId': typeof AdminAdminCustomersEditCustomerIdLazyRoute
  '/_admin/admin/inventory/counts/$countId': typeof AdminAdminInventoryCountsCountIdLazyRoute
  '/_admin/admin/inventory/documents/$documentId': typeof AdminAdminInventoryDocumentsDocumentIdLazyRoute
  '/_admin/admin/inventory/documents/entry': typeof AdminAdminInventoryDocumentsEntryLazyRoute
  '/_admin/admin/inventory/documents/exit': typeof AdminAdminInventoryDocumentsExitLazyRoute
  '/_admin/admin/inventory/items/create': typeof AdminAdminInventoryItemsCreateLazyRoute
  '/_admin/admin/inventory/transfers/$transferId': typeof AdminAdminInventoryTransfersTransferIdLazyRoute
  '/_admin/admin/inventory/transfers/create': typeof AdminAdminInventoryTransfersCreateLazyRoute
  '/_admin/admin/pets/edit/$petId': typeof AdminAdminPetsEditPetIdLazyRoute
  '/_admin/admin/services/auto/create': typeof AdminAdminServicesAutoCreateLazyRoute
  '/_admin/admin/services/pet/create': typeof AdminAdminServicesPetCreateLazyRoute
  '/_admin/admin/users/edit/$userId': typeof AdminAdminUsersEditUserIdLazyRoute
  '/_admin/admin/vehicles/edit/$vehicleId': typeof AdminAdminVehiclesEditVehicleIdLazyRoute
  '/_admin/admin/catalogs/breeds/': typeof AdminAdminCatalogsBreedsIndexLazyRoute
  '/_admin/admin/catalogs/vehicles/': typeof AdminAdminCatalogsVehiclesIndexLazyRoute
  '/_admin/admin/inventory/catalogs/': typeof AdminAdminInventoryCatalogsIndexLazyRoute
  '/_admin/admin/inventory/counts/': typeof AdminAdminInventoryCountsIndexLazyRoute
  '/_admin/admin/inventory/documents/': typeof AdminAdminInventoryDocumentsIndexLazyRoute
  '/_admin/admin/inventory/items/': typeof AdminAdminInventoryItemsIndexLazyRoute
  '/_admin/admin/inventory/panel/': typeof AdminAdminInventoryPanelIndexLazyRoute
  '/_admin/admin/inventory/suppliers/': typeof AdminAdminInventorySuppliersIndexLazyRoute
  '/_admin/admin/inventory/transfers/': typeof AdminAdminInventoryTransfersIndexLazyRoute
  '/_admin/admin/services/auto/': typeof AdminAdminServicesAutoIndexLazyRoute
  '/_admin/admin/services/pet/': typeof AdminAdminServicesPetIndexLazyRoute
  '/_admin/admin/inventory/items/edit/$itemId': typeof AdminAdminInventoryItemsEditItemIdLazyRoute
  '/_admin/admin/services/auto/edit/$serviceId': typeof AdminAdminServicesAutoEditServiceIdLazyRoute
  '/_admin/admin/services/pet/edit/$serviceId': typeof AdminAdminServicesPetEditServiceIdLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/roles'
    | '/admin/security'
    | '/admin/'
    | '/admin/customers/create'
    | '/admin/inventory/quick-exit'
    | '/admin/locations/$locationId'
    | '/admin/pets/create'
    | '/admin/users/create'
    | '/admin/vehicles/create'
    | '/admin/customers/'
    | '/admin/locations/'
    | '/admin/pets/'
    | '/admin/users/'
    | '/admin/vehicles/'
    | '/admin/catalogs/vehicles/$makeId'
    | '/admin/customers/edit/$customerId'
    | '/admin/inventory/counts/$countId'
    | '/admin/inventory/documents/$documentId'
    | '/admin/inventory/documents/entry'
    | '/admin/inventory/documents/exit'
    | '/admin/inventory/items/create'
    | '/admin/inventory/transfers/$transferId'
    | '/admin/inventory/transfers/create'
    | '/admin/pets/edit/$petId'
    | '/admin/services/auto/create'
    | '/admin/services/pet/create'
    | '/admin/users/edit/$userId'
    | '/admin/vehicles/edit/$vehicleId'
    | '/admin/catalogs/breeds/'
    | '/admin/catalogs/vehicles/'
    | '/admin/inventory/catalogs/'
    | '/admin/inventory/counts/'
    | '/admin/inventory/documents/'
    | '/admin/inventory/items/'
    | '/admin/inventory/panel/'
    | '/admin/inventory/suppliers/'
    | '/admin/inventory/transfers/'
    | '/admin/services/auto/'
    | '/admin/services/pet/'
    | '/admin/inventory/items/edit/$itemId'
    | '/admin/services/auto/edit/$serviceId'
    | '/admin/services/pet/edit/$serviceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/dashboard'
    | '/admin/profile'
    | '/admin/roles'
    | '/admin/security'
    | '/admin'
    | '/admin/customers/create'
    | '/admin/inventory/quick-exit'
    | '/admin/locations/$locationId'
    | '/admin/pets/create'
    | '/admin/users/create'
    | '/admin/vehicles/create'
    | '/admin/customers'
    | '/admin/locations'
    | '/admin/pets'
    | '/admin/users'
    | '/admin/vehicles'
    | '/admin/catalogs/vehicles/$makeId'
    | '/admin/customers/edit/$customerId'
    | '/admin/inventory/counts/$countId'
    | '/admin/inventory/documents/$documentId'
    | '/admin/inventory/documents/entry'
    | '/admin/inventory/documents/exit'
    | '/admin/inventory/items/create'
    | '/admin/inventory/transfers/$transferId'
    | '/admin/inventory/transfers/create'
    | '/admin/pets/edit/$petId'
    | '/admin/services/auto/create'
    | '/admin/services/pet/create'
    | '/admin/users/edit/$userId'
    | '/admin/vehicles/edit/$vehicleId'
    | '/admin/catalogs/breeds'
    | '/admin/catalogs/vehicles'
    | '/admin/inventory/catalogs'
    | '/admin/inventory/counts'
    | '/admin/inventory/documents'
    | '/admin/inventory/items'
    | '/admin/inventory/panel'
    | '/admin/inventory/suppliers'
    | '/admin/inventory/transfers'
    | '/admin/services/auto'
    | '/admin/services/pet'
    | '/admin/inventory/items/edit/$itemId'
    | '/admin/services/auto/edit/$serviceId'
    | '/admin/services/pet/edit/$serviceId'
  id:
    | '__root__'
    | '/'
    | '/_admin'
    | '/_auth'
    | '/_auth/login'
    | '/_admin/admin/dashboard'
    | '/_admin/admin/profile'
    | '/_admin/admin/roles'
    | '/_admin/admin/security'
    | '/_admin/admin/'
    | '/_admin/admin/customers/create'
    | '/_admin/admin/inventory/quick-exit'
    | '/_admin/admin/locations/$locationId'
    | '/_admin/admin/pets/create'
    | '/_admin/admin/users/create'
    | '/_admin/admin/vehicles/create'
    | '/_admin/admin/customers/'
    | '/_admin/admin/locations/'
    | '/_admin/admin/pets/'
    | '/_admin/admin/users/'
    | '/_admin/admin/vehicles/'
    | '/_admin/admin/catalogs/vehicles/$makeId'
    | '/_admin/admin/customers/edit/$customerId'
    | '/_admin/admin/inventory/counts/$countId'
    | '/_admin/admin/inventory/documents/$documentId'
    | '/_admin/admin/inventory/documents/entry'
    | '/_admin/admin/inventory/documents/exit'
    | '/_admin/admin/inventory/items/create'
    | '/_admin/admin/inventory/transfers/$transferId'
    | '/_admin/admin/inventory/transfers/create'
    | '/_admin/admin/pets/edit/$petId'
    | '/_admin/admin/services/auto/create'
    | '/_admin/admin/services/pet/create'
    | '/_admin/admin/users/edit/$userId'
    | '/_admin/admin/vehicles/edit/$vehicleId'
    | '/_admin/admin/catalogs/breeds/'
    | '/_admin/admin/catalogs/vehicles/'
    | '/_admin/admin/inventory/catalogs/'
    | '/_admin/admin/inventory/counts/'
    | '/_admin/admin/inventory/documents/'
    | '/_admin/admin/inventory/items/'
    | '/_admin/admin/inventory/panel/'
    | '/_admin/admin/inventory/suppliers/'
    | '/_admin/admin/inventory/transfers/'
    | '/_admin/admin/services/auto/'
    | '/_admin/admin/services/pet/'
    | '/_admin/admin/inventory/items/edit/$itemId'
    | '/_admin/admin/services/auto/edit/$serviceId'
    | '/_admin/admin/services/pet/edit/$serviceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginLazyRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_admin/admin/': {
      id: '/_admin/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminAdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/security': {
      id: '/_admin/admin/security'
      path: '/admin/security'
      fullPath: '/admin/security'
      preLoaderRoute: typeof AdminAdminSecurityLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/roles': {
      id: '/_admin/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminAdminRolesLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/profile': {
      id: '/_admin/admin/profile'
      path: '/admin/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminAdminProfileLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/dashboard': {
      id: '/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAdminDashboardLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/vehicles/': {
      id: '/_admin/admin/vehicles/'
      path: '/admin/vehicles'
      fullPath: '/admin/vehicles/'
      preLoaderRoute: typeof AdminAdminVehiclesIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/': {
      id: '/_admin/admin/users/'
      path: '/admin/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminAdminUsersIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pets/': {
      id: '/_admin/admin/pets/'
      path: '/admin/pets'
      fullPath: '/admin/pets/'
      preLoaderRoute: typeof AdminAdminPetsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/locations/': {
      id: '/_admin/admin/locations/'
      path: '/admin/locations'
      fullPath: '/admin/locations/'
      preLoaderRoute: typeof AdminAdminLocationsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers/': {
      id: '/_admin/admin/customers/'
      path: '/admin/customers'
      fullPath: '/admin/customers/'
      preLoaderRoute: typeof AdminAdminCustomersIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/vehicles/create': {
      id: '/_admin/admin/vehicles/create'
      path: '/admin/vehicles/create'
      fullPath: '/admin/vehicles/create'
      preLoaderRoute: typeof AdminAdminVehiclesCreateLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/create': {
      id: '/_admin/admin/users/create'
      path: '/admin/users/create'
      fullPath: '/admin/users/create'
      preLoaderRoute: typeof AdminAdminUsersCreateLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pets/create': {
      id: '/_admin/admin/pets/create'
      path: '/admin/pets/create'
      fullPath: '/admin/pets/create'
      preLoaderRoute: typeof AdminAdminPetsCreateLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/locations/$locationId': {
      id: '/_admin/admin/locations/$locationId'
      path: '/admin/locations/$locationId'
      fullPath: '/admin/locations/$locationId'
      preLoaderRoute: typeof AdminAdminLocationsLocationIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/quick-exit': {
      id: '/_admin/admin/inventory/quick-exit'
      path: '/admin/inventory/quick-exit'
      fullPath: '/admin/inventory/quick-exit'
      preLoaderRoute: typeof AdminAdminInventoryQuickExitLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers/create': {
      id: '/_admin/admin/customers/create'
      path: '/admin/customers/create'
      fullPath: '/admin/customers/create'
      preLoaderRoute: typeof AdminAdminCustomersCreateLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/services/pet/': {
      id: '/_admin/admin/services/pet/'
      path: '/admin/services/pet'
      fullPath: '/admin/services/pet/'
      preLoaderRoute: typeof AdminAdminServicesPetIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/services/auto/': {
      id: '/_admin/admin/services/auto/'
      path: '/admin/services/auto'
      fullPath: '/admin/services/auto/'
      preLoaderRoute: typeof AdminAdminServicesAutoIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/transfers/': {
      id: '/_admin/admin/inventory/transfers/'
      path: '/admin/inventory/transfers'
      fullPath: '/admin/inventory/transfers/'
      preLoaderRoute: typeof AdminAdminInventoryTransfersIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/suppliers/': {
      id: '/_admin/admin/inventory/suppliers/'
      path: '/admin/inventory/suppliers'
      fullPath: '/admin/inventory/suppliers/'
      preLoaderRoute: typeof AdminAdminInventorySuppliersIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/panel/': {
      id: '/_admin/admin/inventory/panel/'
      path: '/admin/inventory/panel'
      fullPath: '/admin/inventory/panel/'
      preLoaderRoute: typeof AdminAdminInventoryPanelIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/items/': {
      id: '/_admin/admin/inventory/items/'
      path: '/admin/inventory/items'
      fullPath: '/admin/inventory/items/'
      preLoaderRoute: typeof AdminAdminInventoryItemsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/documents/': {
      id: '/_admin/admin/inventory/documents/'
      path: '/admin/inventory/documents'
      fullPath: '/admin/inventory/documents/'
      preLoaderRoute: typeof AdminAdminInventoryDocumentsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/counts/': {
      id: '/_admin/admin/inventory/counts/'
      path: '/admin/inventory/counts'
      fullPath: '/admin/inventory/counts/'
      preLoaderRoute: typeof AdminAdminInventoryCountsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/catalogs/': {
      id: '/_admin/admin/inventory/catalogs/'
      path: '/admin/inventory/catalogs'
      fullPath: '/admin/inventory/catalogs/'
      preLoaderRoute: typeof AdminAdminInventoryCatalogsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/catalogs/vehicles/': {
      id: '/_admin/admin/catalogs/vehicles/'
      path: '/admin/catalogs/vehicles'
      fullPath: '/admin/catalogs/vehicles/'
      preLoaderRoute: typeof AdminAdminCatalogsVehiclesIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/catalogs/breeds/': {
      id: '/_admin/admin/catalogs/breeds/'
      path: '/admin/catalogs/breeds'
      fullPath: '/admin/catalogs/breeds/'
      preLoaderRoute: typeof AdminAdminCatalogsBreedsIndexLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/vehicles/edit/$vehicleId': {
      id: '/_admin/admin/vehicles/edit/$vehicleId'
      path: '/admin/vehicles/edit/$vehicleId'
      fullPath: '/admin/vehicles/edit/$vehicleId'
      preLoaderRoute: typeof AdminAdminVehiclesEditVehicleIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/users/edit/$userId': {
      id: '/_admin/admin/users/edit/$userId'
      path: '/admin/users/edit/$userId'
      fullPath: '/admin/users/edit/$userId'
      preLoaderRoute: typeof AdminAdminUsersEditUserIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/services/pet/create': {
      id: '/_admin/admin/services/pet/create'
      path: '/admin/services/pet/create'
      fullPath: '/admin/services/pet/create'
      preLoaderRoute: typeof AdminAdminServicesPetCreateLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/services/auto/create': {
      id: '/_admin/admin/services/auto/create'
      path: '/admin/services/auto/create'
      fullPath: '/admin/services/auto/create'
      preLoaderRoute: typeof AdminAdminServicesAutoCreateLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/pets/edit/$petId': {
      id: '/_admin/admin/pets/edit/$petId'
      path: '/admin/pets/edit/$petId'
      fullPath: '/admin/pets/edit/$petId'
      preLoaderRoute: typeof AdminAdminPetsEditPetIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/transfers/create': {
      id: '/_admin/admin/inventory/transfers/create'
      path: '/admin/inventory/transfers/create'
      fullPath: '/admin/inventory/transfers/create'
      preLoaderRoute: typeof AdminAdminInventoryTransfersCreateLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/transfers/$transferId': {
      id: '/_admin/admin/inventory/transfers/$transferId'
      path: '/admin/inventory/transfers/$transferId'
      fullPath: '/admin/inventory/transfers/$transferId'
      preLoaderRoute: typeof AdminAdminInventoryTransfersTransferIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/items/create': {
      id: '/_admin/admin/inventory/items/create'
      path: '/admin/inventory/items/create'
      fullPath: '/admin/inventory/items/create'
      preLoaderRoute: typeof AdminAdminInventoryItemsCreateLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/documents/exit': {
      id: '/_admin/admin/inventory/documents/exit'
      path: '/admin/inventory/documents/exit'
      fullPath: '/admin/inventory/documents/exit'
      preLoaderRoute: typeof AdminAdminInventoryDocumentsExitLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/documents/entry': {
      id: '/_admin/admin/inventory/documents/entry'
      path: '/admin/inventory/documents/entry'
      fullPath: '/admin/inventory/documents/entry'
      preLoaderRoute: typeof AdminAdminInventoryDocumentsEntryLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/documents/$documentId': {
      id: '/_admin/admin/inventory/documents/$documentId'
      path: '/admin/inventory/documents/$documentId'
      fullPath: '/admin/inventory/documents/$documentId'
      preLoaderRoute: typeof AdminAdminInventoryDocumentsDocumentIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/counts/$countId': {
      id: '/_admin/admin/inventory/counts/$countId'
      path: '/admin/inventory/counts/$countId'
      fullPath: '/admin/inventory/counts/$countId'
      preLoaderRoute: typeof AdminAdminInventoryCountsCountIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/customers/edit/$customerId': {
      id: '/_admin/admin/customers/edit/$customerId'
      path: '/admin/customers/edit/$customerId'
      fullPath: '/admin/customers/edit/$customerId'
      preLoaderRoute: typeof AdminAdminCustomersEditCustomerIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/catalogs/vehicles/$makeId': {
      id: '/_admin/admin/catalogs/vehicles/$makeId'
      path: '/admin/catalogs/vehicles/$makeId'
      fullPath: '/admin/catalogs/vehicles/$makeId'
      preLoaderRoute: typeof AdminAdminCatalogsVehiclesMakeIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/services/pet/edit/$serviceId': {
      id: '/_admin/admin/services/pet/edit/$serviceId'
      path: '/admin/services/pet/edit/$serviceId'
      fullPath: '/admin/services/pet/edit/$serviceId'
      preLoaderRoute: typeof AdminAdminServicesPetEditServiceIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/services/auto/edit/$serviceId': {
      id: '/_admin/admin/services/auto/edit/$serviceId'
      path: '/admin/services/auto/edit/$serviceId'
      fullPath: '/admin/services/auto/edit/$serviceId'
      preLoaderRoute: typeof AdminAdminServicesAutoEditServiceIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/admin/inventory/items/edit/$itemId': {
      id: '/_admin/admin/inventory/items/edit/$itemId'
      path: '/admin/inventory/items/edit/$itemId'
      fullPath: '/admin/inventory/items/edit/$itemId'
      preLoaderRoute: typeof AdminAdminInventoryItemsEditItemIdLazyRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminAdminDashboardLazyRoute: typeof AdminAdminDashboardLazyRoute
  AdminAdminProfileLazyRoute: typeof AdminAdminProfileLazyRoute
  AdminAdminRolesLazyRoute: typeof AdminAdminRolesLazyRoute
  AdminAdminSecurityLazyRoute: typeof AdminAdminSecurityLazyRoute
  AdminAdminIndexRoute: typeof AdminAdminIndexRoute
  AdminAdminCustomersCreateLazyRoute: typeof AdminAdminCustomersCreateLazyRoute
  AdminAdminInventoryQuickExitLazyRoute: typeof AdminAdminInventoryQuickExitLazyRoute
  AdminAdminLocationsLocationIdLazyRoute: typeof AdminAdminLocationsLocationIdLazyRoute
  AdminAdminPetsCreateLazyRoute: typeof AdminAdminPetsCreateLazyRoute
  AdminAdminUsersCreateLazyRoute: typeof AdminAdminUsersCreateLazyRoute
  AdminAdminVehiclesCreateLazyRoute: typeof AdminAdminVehiclesCreateLazyRoute
  AdminAdminCustomersIndexLazyRoute: typeof AdminAdminCustomersIndexLazyRoute
  AdminAdminLocationsIndexLazyRoute: typeof AdminAdminLocationsIndexLazyRoute
  AdminAdminPetsIndexLazyRoute: typeof AdminAdminPetsIndexLazyRoute
  AdminAdminUsersIndexLazyRoute: typeof AdminAdminUsersIndexLazyRoute
  AdminAdminVehiclesIndexLazyRoute: typeof AdminAdminVehiclesIndexLazyRoute
  AdminAdminCatalogsVehiclesMakeIdLazyRoute: typeof AdminAdminCatalogsVehiclesMakeIdLazyRoute
  AdminAdminCustomersEditCustomerIdLazyRoute: typeof AdminAdminCustomersEditCustomerIdLazyRoute
  AdminAdminInventoryCountsCountIdLazyRoute: typeof AdminAdminInventoryCountsCountIdLazyRoute
  AdminAdminInventoryDocumentsDocumentIdLazyRoute: typeof AdminAdminInventoryDocumentsDocumentIdLazyRoute
  AdminAdminInventoryDocumentsEntryLazyRoute: typeof AdminAdminInventoryDocumentsEntryLazyRoute
  AdminAdminInventoryDocumentsExitLazyRoute: typeof AdminAdminInventoryDocumentsExitLazyRoute
  AdminAdminInventoryItemsCreateLazyRoute: typeof AdminAdminInventoryItemsCreateLazyRoute
  AdminAdminInventoryTransfersTransferIdLazyRoute: typeof AdminAdminInventoryTransfersTransferIdLazyRoute
  AdminAdminInventoryTransfersCreateLazyRoute: typeof AdminAdminInventoryTransfersCreateLazyRoute
  AdminAdminPetsEditPetIdLazyRoute: typeof AdminAdminPetsEditPetIdLazyRoute
  AdminAdminServicesAutoCreateLazyRoute: typeof AdminAdminServicesAutoCreateLazyRoute
  AdminAdminServicesPetCreateLazyRoute: typeof AdminAdminServicesPetCreateLazyRoute
  AdminAdminUsersEditUserIdLazyRoute: typeof AdminAdminUsersEditUserIdLazyRoute
  AdminAdminVehiclesEditVehicleIdLazyRoute: typeof AdminAdminVehiclesEditVehicleIdLazyRoute
  AdminAdminCatalogsBreedsIndexLazyRoute: typeof AdminAdminCatalogsBreedsIndexLazyRoute
  AdminAdminCatalogsVehiclesIndexLazyRoute: typeof AdminAdminCatalogsVehiclesIndexLazyRoute
  AdminAdminInventoryCatalogsIndexLazyRoute: typeof AdminAdminInventoryCatalogsIndexLazyRoute
  AdminAdminInventoryCountsIndexLazyRoute: typeof AdminAdminInventoryCountsIndexLazyRoute
  AdminAdminInventoryDocumentsIndexLazyRoute: typeof AdminAdminInventoryDocumentsIndexLazyRoute
  AdminAdminInventoryItemsIndexLazyRoute: typeof AdminAdminInventoryItemsIndexLazyRoute
  AdminAdminInventoryPanelIndexLazyRoute: typeof AdminAdminInventoryPanelIndexLazyRoute
  AdminAdminInventorySuppliersIndexLazyRoute: typeof AdminAdminInventorySuppliersIndexLazyRoute
  AdminAdminInventoryTransfersIndexLazyRoute: typeof AdminAdminInventoryTransfersIndexLazyRoute
  AdminAdminServicesAutoIndexLazyRoute: typeof AdminAdminServicesAutoIndexLazyRoute
  AdminAdminServicesPetIndexLazyRoute: typeof AdminAdminServicesPetIndexLazyRoute
  AdminAdminInventoryItemsEditItemIdLazyRoute: typeof AdminAdminInventoryItemsEditItemIdLazyRoute
  AdminAdminServicesAutoEditServiceIdLazyRoute: typeof AdminAdminServicesAutoEditServiceIdLazyRoute
  AdminAdminServicesPetEditServiceIdLazyRoute: typeof AdminAdminServicesPetEditServiceIdLazyRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardLazyRoute: AdminAdminDashboardLazyRoute,
  AdminAdminProfileLazyRoute: AdminAdminProfileLazyRoute,
  AdminAdminRolesLazyRoute: AdminAdminRolesLazyRoute,
  AdminAdminSecurityLazyRoute: AdminAdminSecurityLazyRoute,
  AdminAdminIndexRoute: AdminAdminIndexRoute,
  AdminAdminCustomersCreateLazyRoute: AdminAdminCustomersCreateLazyRoute,
  AdminAdminInventoryQuickExitLazyRoute: AdminAdminInventoryQuickExitLazyRoute,
  AdminAdminLocationsLocationIdLazyRoute:
    AdminAdminLocationsLocationIdLazyRoute,
  AdminAdminPetsCreateLazyRoute: AdminAdminPetsCreateLazyRoute,
  AdminAdminUsersCreateLazyRoute: AdminAdminUsersCreateLazyRoute,
  AdminAdminVehiclesCreateLazyRoute: AdminAdminVehiclesCreateLazyRoute,
  AdminAdminCustomersIndexLazyRoute: AdminAdminCustomersIndexLazyRoute,
  AdminAdminLocationsIndexLazyRoute: AdminAdminLocationsIndexLazyRoute,
  AdminAdminPetsIndexLazyRoute: AdminAdminPetsIndexLazyRoute,
  AdminAdminUsersIndexLazyRoute: AdminAdminUsersIndexLazyRoute,
  AdminAdminVehiclesIndexLazyRoute: AdminAdminVehiclesIndexLazyRoute,
  AdminAdminCatalogsVehiclesMakeIdLazyRoute:
    AdminAdminCatalogsVehiclesMakeIdLazyRoute,
  AdminAdminCustomersEditCustomerIdLazyRoute:
    AdminAdminCustomersEditCustomerIdLazyRoute,
  AdminAdminInventoryCountsCountIdLazyRoute:
    AdminAdminInventoryCountsCountIdLazyRoute,
  AdminAdminInventoryDocumentsDocumentIdLazyRoute:
    AdminAdminInventoryDocumentsDocumentIdLazyRoute,
  AdminAdminInventoryDocumentsEntryLazyRoute:
    AdminAdminInventoryDocumentsEntryLazyRoute,
  AdminAdminInventoryDocumentsExitLazyRoute:
    AdminAdminInventoryDocumentsExitLazyRoute,
  AdminAdminInventoryItemsCreateLazyRoute:
    AdminAdminInventoryItemsCreateLazyRoute,
  AdminAdminInventoryTransfersTransferIdLazyRoute:
    AdminAdminInventoryTransfersTransferIdLazyRoute,
  AdminAdminInventoryTransfersCreateLazyRoute:
    AdminAdminInventoryTransfersCreateLazyRoute,
  AdminAdminPetsEditPetIdLazyRoute: AdminAdminPetsEditPetIdLazyRoute,
  AdminAdminServicesAutoCreateLazyRoute: AdminAdminServicesAutoCreateLazyRoute,
  AdminAdminServicesPetCreateLazyRoute: AdminAdminServicesPetCreateLazyRoute,
  AdminAdminUsersEditUserIdLazyRoute: AdminAdminUsersEditUserIdLazyRoute,
  AdminAdminVehiclesEditVehicleIdLazyRoute:
    AdminAdminVehiclesEditVehicleIdLazyRoute,
  AdminAdminCatalogsBreedsIndexLazyRoute:
    AdminAdminCatalogsBreedsIndexLazyRoute,
  AdminAdminCatalogsVehiclesIndexLazyRoute:
    AdminAdminCatalogsVehiclesIndexLazyRoute,
  AdminAdminInventoryCatalogsIndexLazyRoute:
    AdminAdminInventoryCatalogsIndexLazyRoute,
  AdminAdminInventoryCountsIndexLazyRoute:
    AdminAdminInventoryCountsIndexLazyRoute,
  AdminAdminInventoryDocumentsIndexLazyRoute:
    AdminAdminInventoryDocumentsIndexLazyRoute,
  AdminAdminInventoryItemsIndexLazyRoute:
    AdminAdminInventoryItemsIndexLazyRoute,
  AdminAdminInventoryPanelIndexLazyRoute:
    AdminAdminInventoryPanelIndexLazyRoute,
  AdminAdminInventorySuppliersIndexLazyRoute:
    AdminAdminInventorySuppliersIndexLazyRoute,
  AdminAdminInventoryTransfersIndexLazyRoute:
    AdminAdminInventoryTransfersIndexLazyRoute,
  AdminAdminServicesAutoIndexLazyRoute: AdminAdminServicesAutoIndexLazyRoute,
  AdminAdminServicesPetIndexLazyRoute: AdminAdminServicesPetIndexLazyRoute,
  AdminAdminInventoryItemsEditItemIdLazyRoute:
    AdminAdminInventoryItemsEditItemIdLazyRoute,
  AdminAdminServicesAutoEditServiceIdLazyRoute:
    AdminAdminServicesAutoEditServiceIdLazyRoute,
  AdminAdminServicesPetEditServiceIdLazyRoute:
    AdminAdminServicesPetEditServiceIdLazyRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AuthRouteChildren {
  AuthLoginLazyRoute: typeof AuthLoginLazyRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthLoginLazyRoute: AuthLoginLazyRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
